// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceWatcher.Infrastructure.Data;

#nullable disable

namespace PriceWatcher.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PriceWatcherDbContext))]
    [Migration("20260104143921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("PriceWatcher.Infrastructure.Data.Entities.BotState", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TelegramUserId");

                    b.ToTable("BotStates");
                });

            modelBuilder.Entity("PriceWatcher.Infrastructure.Data.Entities.PriceEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawText")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackedItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackedItemId", "Timestamp");

                    b.ToTable("PriceEvents");
                });

            modelBuilder.Entity("PriceWatcher.Infrastructure.Data.Entities.TrackedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastCheckAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastErrorNotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastKnownPriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TrackedItems");
                });

            modelBuilder.Entity("PriceWatcher.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PriceWatcher.Infrastructure.Data.Entities.PriceEvent", b =>
                {
                    b.HasOne("PriceWatcher.Infrastructure.Data.Entities.TrackedItem", "TrackedItem")
                        .WithMany("PriceEvents")
                        .HasForeignKey("TrackedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedItem");
                });

            modelBuilder.Entity("PriceWatcher.Infrastructure.Data.Entities.TrackedItem", b =>
                {
                    b.HasOne("PriceWatcher.Infrastructure.Data.Entities.User", "User")
                        .WithMany("TrackedItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PriceWatcher.Infrastructure.Data.Entities.TrackedItem", b =>
                {
                    b.Navigation("PriceEvents");
                });

            modelBuilder.Entity("PriceWatcher.Infrastructure.Data.Entities.User", b =>
                {
                    b.Navigation("TrackedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
